#!/usr/bin/env python3
import os, sys

_srcdir = '%s/src/' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    import acmpv
    if __name__ == '__main__':
        acmpv.main()
else: # Python 2
    print("[fatal] Python 3 is required!")
    print("try to run this script using 'python3 acmpv'.")

